name: CI

on: [pull_request]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: go fmt
        run: |
          go fmt ./...
          [ -z "$( git status --porcelain )" ]
      - name: go vet
        run: go vet ./...
