name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/Songmu/goxz/cmd/goxz@latest
          go install github.com/tcnksm/ghr@latest
          release_tag=$( git describe --abbrev=0 --tags )
          goxz -d dist/$release_tag -z -os windows,linux -arch amd64,386
          goxz -d dist/$release_tag -z -os darwin -arch amd64
          ghr -u nabeo -r mackerel-plugin-aws-transitgateway-attachment $release_tag dist/$release_tag
